### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by TheRedBull** [Ents24/testcafe-browser-provider-fbsimctl#6]
Still really new so I apologize for a potentially dumb question -- are there additional steps to install and configure this addon? I got the following error and am not sure where to go with it:

 ```
ERROR TypeError: Cannot read property 'name' of undefined
    at ../node_modules/testcafe-browser-provider-fbsimctl/lib/index.js:279:107
    at Array.filter (native)
    at BrowserProviderPluginHost._getDeviceFromDetails (../node_modules/testcafe-browser-provider-fbsimctl/lib/index.js:278:42)
    at BrowserProviderPluginHost._callee5$ (../node_modules/testcafe-browser-provider-fbsimctl/lib/index.js:158:70)
    at tryCatch (../node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:117:21)
    at step (../node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at ../node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise (<anonymous>)
```

**Comment by HenningThiemann** [comment]
@TheRedBull I do not know if you have solved your problem yet, but I ran into the same issue today. 

My problem was that there were several Xcode simulated devices with the same names but different iOS versions on it. The provider obviously can not handle this.
If you make sure that your device names are unique, this error should not be happening anymore.
